#!/usr/bin/env python3
"""WORKBOOK -> DRAFT. The missing link in Saturday's path. [2026-08-13]

    python tools/dictation/workbook_to_draft.py <workbook.xlsx> [-o <draft.json>]

WHY THIS EXISTS. Mike writes the Records in an Excel workbook — one sheet per
day, a headline, two deck lines and up to six label/text section pairs. The
lander (`npm run record:land`) reads a DRAFT JSON. **Nothing joined the two.**
Until tonight the join was a person retyping five records into a JSON file,
which is the step where a character goes missing.

IT IS PYTHON AND NOT NODE FOR ONE REASON: `openpyxl` is installed on this
machine and no JavaScript xlsx reader is. Adding a node dependency to read one
file once a week is a worse trade than one small script in the language that
already has the library.

═══ WHAT IT READS, AND WHY IT IS READ BY POSITION ═══════════════════════════
The workbook is generated by `build-record-workbook.py`, so its shape is fixed:

    row  4   THE HEADLINE          -> title
    row  5   THE DECK — line 1     -> line, first half
    row  6   THE DECK — line 2     -> line, second half (joined with \\n)
    rows 9,12,15,18,21,24   Section N — LABEL
    rows 10,13,16,19,22,25  Section N — TEXT

**The labels in column A are CHECKED, not assumed.** If a row's label is not
what this reader expects, it says so and stops rather than reading the wrong
cell — a workbook whose rows have shifted by one would otherwise land the deck
as a headline, silently.

═══ THE TWO CONVERSIONS THAT MATTER ════════════════════════════════════════
  · A BLANK LINE SEPARATES PARAGRAPHS inside a TEXT cell. That is the
    convention the workbook itself prints in its own instructions, so it is the
    one implemented here. A single newline inside a paragraph is preserved as
    part of that paragraph.
  · THE DECK IS TWO LINES JOINED BY \\n, because `.vp-rec-sum` has
    `white-space: pre-line` and Mike's ruling is that the deck is always two
    lines and never wraps.

═══ WHAT IT REFUSES ════════════════════════════════════════════════════════
  · a sheet whose row labels do not match
  · a headline over RECORD_TITLE_MAX or a deck over RECORD_LINE_MAX — the two
    limits the workbook counts in its own column D. It reports and CONTINUES on
    these, because the workbook already warned him and the gate will refuse
    later; stopping here would hide the other four days' problems.
  · nothing else. It is a reader, not a judge.
"""
import argparse
import datetime
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

ROW_HEADLINE = 4
ROW_DECK_1 = 5
ROW_DECK_2 = 6
SECTION_ROWS = [(9, 10), (12, 13), (15, 16), (18, 19), (21, 22), (24, 25)]

# what column A must say on each row we read. The check that stops a shifted
# workbook from landing the wrong cell into the wrong field.
#
# [F 2026-08-13] AND IT NOW COVERS THE TWELVE SECTION ROWS, WHICH WERE THE
# UNGUARDED FIFTEEN-SIXTEENTHS OF THE SHEET.
# THE HOLE, STATED EXACTLY: the guard read rows 4, 5 and 6 only. Everything a
# section is made of lives at rows 9-25, so a workbook whose shape moved BELOW
# row 8 — one inserted row above THE SECTIONS, a slot added, a day's tab rebuilt
# by hand — passed the guard and then read every label and every paragraph one
# row out. Section 1's label becomes section 1's text, section 2's text becomes
# section 3's label, and NOTHING SAYS SO: the draft is well-formed, the emitter
# is happy, the round-trip proof compares the mangled draft against itself and
# reports his characters unchanged. It is the quietest possible failure on the
# one file he types into, and it was three lines from being impossible.
# EACH ROW IS CHECKED FOR SEVERAL SUBSTRINGS RATHER THAN ONE WHOLE STRING,
# because column A reads "Section 3 — LABEL" with an EM DASH: matching the
# literal would make this guard fail the day somebody retypes the sheet with a
# hyphen, which is a guard that cries wolf and then gets deleted. "Section 3"
# and "LABEL" together cannot land on the wrong row.
EXPECT = {
    ROW_HEADLINE: ["THE HEADLINE"],
    ROW_DECK_1: ["THE DECK"],
    ROW_DECK_2: ["THE DECK"],
}
for _i, (_label_row, _text_row) in enumerate(SECTION_ROWS, start=1):
    EXPECT[_label_row] = [f"Section {_i}", "LABEL"]
    EXPECT[_text_row] = [f"Section {_i}", "TEXT"]

TITLE_MAX = 62
LINE_MAX = 130


def cell(ws, row, col=2):
    v = ws.cell(row=row, column=col).value
    return "" if v is None else str(v)


def paragraphs(text):
    """A blank line separates paragraphs. Trailing whitespace on a line is
    dropped; the paragraph's own internal newlines are kept."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    blocks = re.split(r"\n[ \t]*\n", text)
    return [b.strip("\n").rstrip() for b in blocks if b.strip()]


def read_sheet(ws, name):
    faults = []
    for row, wants in sorted(EXPECT.items()):
        got = cell(ws, row, 1)
        missing = [w for w in wants if w not in got]
        if missing:
            faults.append(
                f"row {row} of '{name}' says {got!r}, expected something containing "
                f"{', '.join(repr(w) for w in missing)}. "
                f"The workbook's shape has moved; this reader will not guess.")
    if faults:
        return None, faults

    m = re.search(r"Record\s+(\d+)", name)
    if not m:
        return None, [f"sheet '{name}' has no record number in its name"]
    no = int(m.group(1))

    title = cell(ws, ROW_HEADLINE).strip()
    d1 = cell(ws, ROW_DECK_1).strip()
    d2 = cell(ws, ROW_DECK_2).strip()
    line = "\n".join([x for x in (d1, d2) if x])

    sections = []
    for label_row, text_row in SECTION_ROWS:
        label = cell(ws, label_row).strip()
        body = paragraphs(cell(ws, text_row))
        # [F 2026-08-13] MIKE'S RULING: "a section whose body is empty after
        # notes are removed is dropped entirely, label included. A bald heading
        # never reaches the page."
        # THE TEST IS THE BODY ALONE. This line used to read `if not label and
        # not body`, so a slot with a LABEL and an empty TEXT cell survived and
        # landed a heading with nothing under it. That is not a hypothetical
        # shape: his notes to Ops live in curly braces, so a section whose only
        # paragraph was a note becomes exactly this the moment the note is acted
        # on and deleted — the heading he wrote for it stays behind, in a
        # workbook cell he has no reason to look at again.
        # A LABEL WITH NO BODY IS DROPPED SILENTLY AND ON PURPOSE. It is not a
        # fault: he is allowed to leave a heading in a slot he did not fill,
        # and refusing the workbook over it would stop Saturday for a cell that
        # means "not this one".
        if not body:
            continue
        sections.append({"label": label or None, "body": body})

    warn = []
    if len(title) > TITLE_MAX:
        warn.append(f"Record {no:03d}: the headline is {len(title)} characters, over {TITLE_MAX}")
    if len(line) > LINE_MAX:
        warn.append(f"Record {no:03d}: the deck is {len(line)} characters, over {LINE_MAX}")

    entry = {"no": no}
    if title:
        entry["title"] = title
    if line:
        entry["line"] = line
    entry["sections"] = sections
    return entry, warn


def record_epoch():
    """The one constant, read rather than re-declared."""
    p = os.path.join(REPO, "src", "data", "artists", "record-epoch.js")
    try:
        src = open(p, encoding="utf-8").read()
    except OSError:
        return None
    m = re.search(r'RECORD_EPOCH\s*=\s*"(\d{4}-\d{2}-\d{2})"', src)
    return m.group(1) if m else None


def day_of(no, epoch):
    if not epoch:
        return None
    d = datetime.date.fromisoformat(epoch) + datetime.timedelta(days=no - 1)
    return d.isoformat()


def tree_entries():
    """The Records already in the tree, read by the museum's own reader.

    THE REHEARSAL FOUND THIS AND IT WOULD HAVE STOPPED SATURDAY DEAD. The
    workbook is `RECORD_days-2-to-6.xlsx` — it covers days 2 to 6 and **Record
    001 is not in it**, because 001 was written before the workbook existed. A
    draft built from the workbook alone therefore drops 001, and guard 3
    refuses the landing outright:

        REFUSED — the draft does not carry record(s) 1, which are in
        src/data/artists/robots-record.js.

    The guard is right: a draft is meant to hold the whole volume. So the draft
    is the TREE overlaid with the workbook — every record the workbook does not
    mention passes through untouched, which is also exactly what the emitter
    needs in order to carry that record's comments through verbatim.
    """
    import subprocess
    js = ("import('./reveal/record-entries.mjs')"
          ".then(m => console.log(JSON.stringify(m.draftEntries().entries)))")
    # `encoding="utf-8"` IS LOAD-BEARING AND THE REHEARSAL FOUND IT. Without it
    # `text=True` decodes node's stdout with the Windows locale codepage
    # (cp1252), and every non-ASCII character in every carried record comes back
    # mojibake: Record 001's deck arrived as `Alert â€” Incoming` instead of
    # `Alert — Incoming`. The lander then reads the record as CHANGED, and had
    # it not carried comments it would have LANDED THE CORRUPTION — em dashes,
    # the `·` separators and every curly quote in the volume, silently.
    try:
        out = subprocess.run(["node", "-e", js], cwd=REPO, capture_output=True,
                             text=True, encoding="utf-8", timeout=120)
    except Exception as e:                                    # noqa: BLE001
        print(f"  !! could not read the tree ({e}); the draft will hold only "
              f"what the workbook carries", file=sys.stderr)
        return []
    if out.returncode != 0:
        print("  !! could not read the tree:", out.stderr.strip()[:200], file=sys.stderr)
        return []
    return json.loads(out.stdout)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("workbook")
    ap.add_argument("-o", "--out", default=None)
    ap.add_argument("--no-merge", action="store_true",
                    help="do NOT overlay onto the tree's records (the draft will "
                         "hold only what the workbook carries, and guard 3 will "
                         "refuse it if the tree holds anything else)")
    a = ap.parse_args()

    try:
        import openpyxl
    except ImportError:
        print("openpyxl is not installed.  pip install openpyxl", file=sys.stderr)
        sys.exit(1)

    wb = openpyxl.load_workbook(a.workbook, data_only=True)
    epoch = record_epoch()
    entries, warnings, faults = [], [], []

    for name in wb.sheetnames:
        if not re.search(r"Record\s+\d+", name):
            continue
        entry, msgs = read_sheet(wb[name], name)
        if entry is None:
            faults.extend(msgs)
            continue
        warnings.extend(msgs)
        # THE DATE IS DERIVED FROM THE ONE EPOCH, never typed. A workbook sheet
        # names a weekday in its own title bar; the entry's date comes from
        # record-epoch.js so that a launch slip moves one line and not five.
        d = day_of(entry["no"], epoch)
        if d:
            entry["date"] = d
        entries.append(entry)

    if faults:
        print("REFUSED — the workbook is not the shape this reader knows:", file=sys.stderr)
        for f in faults:
            print("    " + f, file=sys.stderr)
        sys.exit(1)

    # THE TREE FIRST, THEN THE WORKBOOK OVER IT. A record the workbook does not
    # mention keeps exactly the text the tree holds, which is what lets the
    # emitter splice its comments through byte for byte.
    carried_from_tree = []
    if not a.no_merge:
        from_wb = {e["no"] for e in entries}
        for t in tree_entries():
            if t.get("no") in from_wb:
                continue
            d = day_of(t["no"], epoch)
            if d:
                t["date"] = d
            entries.append(t)
            carried_from_tree.append(t["no"])

    entries.sort(key=lambda e: e["no"])
    draft = {
        "_": "Mike's Records, read out of the workbook by "
             "tools/dictation/workbook_to_draft.py. Fed to `npm run record:land`.",
        "key": "wb.record.2026-08-09",
        "saved": datetime.datetime.now(datetime.timezone.utc)
                 .isoformat().replace("+00:00", "Z"),
        "epoch": epoch,
        "entries": entries,
    }

    out = a.out or os.path.join(REPO, "docs", "dictation-20260807", "record-draft.json")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        json.dump(draft, f, indent=1, ensure_ascii=False)
        f.write("\n")

    print(f"read {a.workbook}")
    print(f"  {len(entries)} record(s): " + " ".join(f"{e['no']:03d}" for e in entries))
    if carried_from_tree:
        print("  carried from the tree (the workbook does not cover them): "
              + " ".join(f"{n:03d}" for n in sorted(carried_from_tree)))
    for e in entries:
        n = sum(len(s["body"]) for s in e["sections"])
        print(f"    {e['no']:03d}  {len(e['sections'])} section(s), {n} paragraph(s)"
              f"   {'headline' if e.get('title') else 'NO HEADLINE'}"
              f"   {'deck' if e.get('line') else 'no deck'}")
    print(f"  day one {epoch}" if epoch else "  !! no RECORD_EPOCH found")
    if warnings:
        print("  WARNINGS (the workbook counted these for him too):")
        for w in warnings:
            print("      " + w)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
