#!/usr/bin/env node
// provenance/assets-declare.mjs — writes provenance/assets.json.
// ============================================================================
// THE COMPENSATING CHECK FOR THE THING A TEXT SWEEP CANNOT SEE.
// ============================================================================
// The largest placeholder ever found in this building was marker lettering
// PAINTED INTO A JPEG (`public/museum.jpg`, /hr/home) naming four rooms that
// never existed. Its page's own DOM text was three words. Every string sweep in
// the museum's history was blind to it by construction; it took a screenshot.
//
// So every image the authored source references is declared here, and the
// declaration a machine cannot make is the one that matters: `textInImage`,
// with `text` saying WHAT IT SAYS. `inspected` records how the claim was made.
// Each entry below was LOOKED AT on 2026-08-04 — contact sheets at 420px per
// tile, plus a full-resolution crop where the lettering was the point.
//
// The distinction the `text` field exists to preserve: lettering that is part
// of a real object (a maker's plate, a machine's own screen) is EVIDENCE and a
// museum prints it. Museum copy painted into a picture is the /hr/home failure.
// Both set textInImage true; only the reader can tell them apart, which is why
// the field is prose and not a boolean alone.
//
//   node provenance/assets-declare.mjs --write

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
/* [C1 2026-08-06] the stage door's prefix — see the note at the disk check. */
import { STAGE_PREFIX } from "../reveal/placement.mjs";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const INSPECTED = "2026-08-04 — contact sheet at 420px/tile; front_screen.png also at full-resolution crop";
const key = (ref) => crypto.createHash("sha256").update(ref).digest("hex").slice(0, 16);

const PHOTO = "the museum's own photographs of its own unit, held in public/robots/reference/";
const HOUSE_ART = "the house's own artwork";
const WAL = "the artist's own public presence; provenance logged per image in docs/WAL_PHOTO_PROVENANCE-20260802.md";
const HOUSE_SLEEVE = "generated by tools/make_house_covers.py on the ROBOTS cover's own geometry (tools/make_robots_cover.py), which that tool re-renders and compares pixel for pixel on every run";
const COVER = "generated by tools/make_unit_covers.py from the museum's own photograph of its own unit, set into the ROBOTS cover's own geometry (tools/make_robots_cover.py)";

const A = [
  // ---- the MGK units, photographed here --------------------------------
  ["/robots/reference/photos/MGK-TWIN_MONITOR_SCREENS_FAMILY_SHOT.png", "VERIFIED", PHOTO, true,
    "The unit's own faceplate: MGK-VIIIp · The Informer · ABEAL. Object lettering, not museum copy."],
  ["/robots/art/wbr-cover-logo.png", "MIKE", HOUSE_ART, true,
    "Weird.Baby · ROBOTS · PURVEYORS OF THE WEIRD — the wing's own cover."],
  ["/WeirdBaby_PhotoID.png", "MIKE", HOUSE_ART, true, "Weird.Baby — the house wordmark."],
  // [A1 2026-08-04] SUPERSEDED AS THE COVER and left on disk unreferenced —
  // register M9. The declaration stays because the file still ships to the edge.
  // [C1 2026-08-06] `/robots/art/mgk-viii-cover.jpg` WAS HERE AND THE FILE IS
  // DELETED. Mike's standing cull: if we are not using it, get rid of it. It was
  // the SUPERSEDED MGK-NIAC cover, carrying a name the wing retired on
  // 2026-08-05 and replaced by mgk-niac-cover.png. M9 kept it on the reading
  // that "a real photograph is not deleted by a cover change" — which protects
  // the PLATE it was cut from (`core_helical.jpg`, still on disk and still the
  // album's badge), not the derived cover itself, which is house artwork the
  // house no longer uses.
  // ---- [A1 2026-08-04] the two machine covers, on the house template -------
  // Two origins in one picture and both are named: the disc is the museum's own
  // photograph of its own unit, the furniture around it is the ROBOTS cover's
  // own geometry, and nothing was drawn that was not one of those two.
  // [Q3 2026-08-05] renamed with the album: the lettering IN the picture is the
  // model number, so the file could not keep the retired name.
  ["/robots/art/mgk-niac-cover.png", "VERIFIED", COVER, true,
    "MGK-NIAC · PURVEYORS OF THE WEIRD — the model number and the house strapline, both set by tools/make_unit_covers.py. The badge photograph carries no lettering."],
  ["/robots/art/mgk-viiip-cover.png", "VERIFIED", COVER, true,
    "MGK-VIIIp · PURVEYORS OF THE WEIRD set by the tool, and inside the badge the unit's OWN faceplate — MGK-VIIIp · The Informer · ABEAL — with the glass reading ABEAL MGK-VIIIp / LOADING SUCCESS. Object lettering, not museum copy."],
  /* [K1 2026-08-07] THE TEN OPERATOR PLATES ARE DELETED, ON MIKE'S RULING —
     *"none are very good, and if that view is ever needed it gets reshot."*
     C-a put the decision to him with the irreversibility stated (the museum
     held the only copies of these ten files) and he answered it. `bench_power`,
     `chest_grille`, `feet_plinth`, `head_lens`, `head_oblique`, `limbs_lower`,
     `matrix_lit`, `parts_drawer`, `slot_mockup`, `torso_unfinished` are off
     disk, out of `asset-table.json` and out of `assets.json`. THE PRECEDENT
     THEY SET IS REVERSED WITH THEM — *"a real photograph the museum owns is
     not deleted on Ops' word"* stands exactly as written; this is not Ops'
     word. `column_lit.jpg` survives because it is a MAINFRAME plate and is on
     the Image Archive wall. */
  ["/robots/reference/mgk-viii/column_lit.jpg", "VERIFIED", PHOTO, false, ""],
  ["/robots/art/viiip.png", "VERIFIED",
    "the front-view photograph with the twin's own framebuffer composited at the measured aperture; provenance in the robots repo's STATE.md, THE NIGHT RUN",
    true, "MGK-VIIIp · The Informer · ABEAL on the faceplate, and the front glass carries the BIOS beat."],
  ["/robots/reference/photos/front_full.png", "VERIFIED", PHOTO, true,
    "Faceplate MGK-VIIIp · The Informer · ABEAL; the glass reads ABEAL MGK-VIIIp / LOADING SUCCESS."],
  ["/robots/reference/photos/front_screen.png", "VERIFIED", PHOTO, true,
    "THE GLASS IS MIRROR-REVERSED IN THIS FILE. It reads right-to-left: '-(A)BEAL MGK-VIIIp )-' / "
    + "'Please Select:' / 'MGK-VIIIp'. Confirmed at full resolution, not an artefact of the contact "
    + "sheet. It is captioned 'The front glass, lit' and is one of the nine plates this wing offers "
    + "as its evidence, so the machine's own words are the thing that is backwards. FOR MIKE: reflect "
    + "the file, or replace the plate."],
  ["/robots/reference/photos/MGK-TWIN_MONITOR_SCREEN_BEZEL.png", "VERIFIED", PHOTO, false, ""],
  ["/robots/reference/photos/top_monitor.png", "VERIFIED", PHOTO, true,
    "Cyan screen text on the top monitor, including 'Waiting for User Input'. The machine's own output."],
  ["/robots/reference/photos/monitor_base.png", "VERIFIED", PHOTO, true,
    "Faceplate MGK-VIIIp · The Informer · ABEAL."],
  ["/robots/reference/photos/unit_new_base.png", "VERIFIED", PHOTO, true,
    "Faceplate MGK-VIIIp · The Informer · ABEAL."],
  ["/robots/reference/photos/rear_power_switch.png", "VERIFIED", PHOTO, false, ""],
  /* [R4 2026-08-05] THE THREE MAINFRAME PLATES, carried across from the robots
     repo's own culled 2021 set (`robots/mgk-viii/plates/2021-03-19/`, Mike's
     cull of 2026-08-03) so the MGK-NIAC album can show the machine it is named
     for instead of the robot that operates it. Same provenance as every other
     plate on that album — the house's own camera, the house's own bench — and
     the crops are the robots repo's, taken under its OBFUSCATION_LAW: cut at
     the cage bars on four sides, no full silhouette, the room cropped out. */
  ["/robots/reference/mgk-viii/core_helical.jpg", "VERIFIED", PHOTO, false, ""],
  ["/robots/reference/mgk-viii/output_row.jpg", "VERIFIED", PHOTO, false, ""],
  ["/robots/reference/mgk-viii/core_meltdown.jpg", "VERIFIED", PHOTO, false, ""],
  /* [K1 2026-08-07] AND THE MANUAL'S TITLE PAGE GOES WITH THEM, on the same
     ruling and with one difference worth writing down: THIS ONE COSTS NOTHING.
     `structure-issue-p1.png` was byte-identical to
     `weird-baby-robots/robots/mgk-viiip/manual/structure/pages/page-01.png`
     (sha256 cfac1d3b…, 100,077 B) — one of sixty-one pages that repo generates
     from `tools/manual_structure_build.py`. The museum was holding a COPY of a
     page whose source is upstream and regenerable, so the delete removes a
     duplicate rather than an original. G1's note below this line used to
     record the file's arrival and the open question its own type raised (M4 —
     it is a render, not a photograph of a print); the question is upstream's,
     and it stays upstream. */

  // ---- the house's own ---------------------------------------------------
  // [A3 2026-08-06] THE HOUSE SLEEVES, ON THE ROBOTS COVER'S OWN GEOMETRY.
  // Mike ruled the robots gray album the standard for everything carrying
  // Weird.Baby's own art. All six are generated rather than composited, and
  // the tool proves it is the same geometry by re-rendering the robots cover
  // through its own layout and comparing pixel for pixel (`--verify`).
  // `vol1_cover_v1.png` is DELETED and its row goes with it: it was the one
  // object in the museum using red display type, and it is replaced rather
  // than kept beside its replacement.
  ["/images/wb/about-cover.png", "MIKE", HOUSE_SLEEVE, true,
    "the WB mark over ABOUT THE / ARTIST / WEIRD.BABY MUSIC — the house's own name and the album's own."],
  ["/images/wb/vol1-cover.png", "MIKE", HOUSE_SLEEVE, true,
    "the WB mark over THE MAKING / OF BOWB V1 / WEIRD.BABY MUSIC — the record's own title."],
  ["/images/foundation/foundation-cover.png", "MIKE", HOUSE_SLEEVE, true,
    "the WB mark over THE / FOUNDATION / THE WEIRD.BABY FOUNDATION — the album's own name."],
  ["/images/wal/worth-a-listen-cover.png", "MIKE", HOUSE_SLEEVE, true,
    "the WB mark over WORTH / A LISTEN / WEIRD.BABY — the room's own name."],
  // [A3] the Foundation's two survivors, RE-RENDERED. They were typographic on
  // the museum's own paper — which is also the carousel's ground, so they had
  // nothing to show but their keyline and vanished at the rack's edges, which
  // is the defect Mike's A3 names. Same square, same border, same setting; the
  // mark is what changed. `faq-cover.png` is DELETED with the album that used
  // it (F4 makes the FAQ a track on two albums rather than an album).
  ["/images/foundation/ledger-cover.png", "MIKE", HOUSE_SLEEVE, true,
    "the WB mark over THE LEDGER / THE WEIRD.BABY FOUNDATION — the album's own name."],
  ["/images/foundation/contribute-cover.png", "MIKE", HOUSE_SLEEVE, true,
    "the WB mark over CONTRIBUTE / THE WEIRD.BABY FOUNDATION — the album's own name."],
  ["/images/wb-merch/sticker.png", "MIKE", "the museum's own shelf item, as listed in its Printful store", true,
    "Weird.Baby — the wordmark, which is what the sticker is."],

  // ---- Worth A Listen ----------------------------------------------------
  ["/images/wal/carsie-blanton-cover.jpg", "VERIFIED", WAL, false, ""],
  ["/images/wal/carsie-blanton-poster.png", "VERIFIED", WAL, true,
    "CARSIE BLANTON — the artist's own poster lettering."],
  ["/images/wal/hunter-root-cover.jpg", "VERIFIED", WAL, false, ""],
  ["/images/wal/hunter-root-plate.jpg", "VERIFIED",
    "cropped from MediaVault MV-HR-20260405-037, the museum's own vault; the crop is logged in STATE.md v41/C4",
    true,
    "The subject's shirt reads CHET VINCENT AND THE MUSIC INDUSTRY across the chest — ANOTHER BAND'S "
    + "NAME, prominent and legible, on the portrait this wing uses to introduce Hunter Root. Nothing "
    + "on the page mentions it. FOR MIKE: keep, crop tighter, or replace."],
  ["/images/wal/jesse-welles-cover.jpg", "VERIFIED", WAL, false, ""],
  ["/images/wal/jesse-welles-plate.webp", "VERIFIED", WAL, false, ""],
  ["/images/wal/mikey-mike-cover.jpg", "VERIFIED", WAL, false, ""],

  // ---- [A3 2026-08-06] TWO ROWS THAT WERE IN assets.json AND NOT IN HERE ----
  // Found by diffing this file against the JSON it writes, which is a check
  // nothing runs: `--write` regenerates the whole register from the array
  // above, so a row added to the JSON by hand is a row the next `--write`
  // SILENTLY DELETES. Both of these were added by hand (P2 and P7, 2026-08-05)
  // and both would have gone. Re-declared here, verbatim from the JSON, so the
  // declarer is the source again. Register M99.
  ["/robots/art/portal-cover.png", "MIKE",
    "the house's own artwork - tools/make_unit_covers.py, on the ROBOTS cover's template. Its badge is a crop of art/viiip.png, which is the museum's own front-view photograph with the twin's own framebuffer composited into the measured portal aperture.",
    true,
    "PORTAL - PURVEYORS OF THE WEIRD - the album's own cover. The badge carries the machine's own opening beat: MGK-VIIIp BIOS, in the unit's own screen font, reading correctly."],
  ["/robots/reference/mgk-viii/cabinet_whole.jpg", "VERIFIED",
    "the museum's own photograph of its own unit, cut from IMG_1526.MOV (the 2021 build video in the CSR archive, SHA-256 20069C47...D97FED) at 00:58.0, cropped to the cabinet's own bounding box 108,142 -> 966,1580 of the rotated 1080x1920 frame. A re-encode, so the source file's GPS tag does not travel.",
    false, ""],
];

const entries = {};
let missing = 0;
for (const [ref, c, s, textInImage, text] of A) {
  /* [C1 2026-08-06] A GOVERNED PICTURE IS DECLARED AT ITS PUBLIC ADDRESS AND
     MAY BE PARKED BEHIND THE STAGE DOOR. V1 made the pull-back a launch-state
     rule: the data declares `/robots/…` and `src/lib/placement.js` computes the
     held prefix, so the FILE for an undelivered picture is under
     `public/held/robots/…` while its DECLARATION stays public — which is what
     keeps this file, `provenance/assets.json` and the source in agreement.
     Checking only the public path reported 28 of these as missing and the next
     `--write` would have declared a tree that does not exist. Both addresses are
     tried, and the prefix is imported rather than typed. */
  if (!fs.existsSync(path.join(REPO, "public" + ref))
    && !fs.existsSync(path.join(REPO, "public" + STAGE_PREFIX + ref))) {
    console.error("MISSING ON DISK:", ref); missing++;
  }
  entries[key(ref)] = { ref, c, s, textInImage, text, inspected: INSPECTED };
}

const out = {
  _: "ASSET REGISTER. Every image the authored source references, with where it came from and "
    + "whether it carries text a string sweep cannot read. See provenance/README.md.",
  entries,
};

/* ═══ [H2 2026-08-06] M99 IS A MECHANISM NOW, AND IT WAS FIVE ROWS AND IS
   FORTY-FIVE ══════════════════════════════════════════════════════════
   A3 (2026-08-06) found five rows in `assets.json` that this file's array did
   not know about, and that the next `--write` would delete all five in silence.
   It was recorded as a HAZARD in OPERATIONS §8 and left as one — "nothing runs
   the diff that finds it; it is ten lines".
   THE HAZARD GREW. This round moved 28 pictures behind the door and declared
   them in the JSON directly, and the drift is now FORTY-FIVE rows: every artist
   cover, every Foundation sleeve, the house mark and every held plate. A
   `--write` today would have deleted almost the whole asset register.
   SO THE DIFF IS RUN HERE, BY THE THING THAT WOULD DO THE DAMAGE, AND IT
   REFUSES. That is the fix, and it is the difference between a note a future
   session might read and a script that cannot do what the note warns about.
   Repairing the DRIFT — folding those 45 declarations back into the array, or
   retiring this generator in favour of the JSON — is a decision about which of
   the two is the source, and that is Mike's: OPEN_ACTIONS H-b.

   ═══ [C1 2026-08-06] H-b IS ANSWERED, AND BY THE ROUND RATHER THAN BY A
   PREFERENCE. THIS FILE IS THE SOURCE. ══════════════════════════════════════
   V1 settled it: the pull-back is a launch-state rule now, the DATA declares a
   governed picture at its PUBLIC address and `src/lib/placement.js` computes the
   stage door's prefix. So the public address is what the sweep sees, what the
   asset table keys on and what this array has said all along — and H2's 28
   hand-edited `/held/…` rows were the drift rather than the record. Folding them
   back means deleting nothing: they are the same twenty-eight pictures at the
   other address.
   AND THAT IS WHY THE REFUSAL BELOW HAD TO LEARN THE SAME RULE THE OTHER TWO
   DID. It compared raw refs, so it read 27 twins as 27 losses and refused a
   regeneration that would have lost exactly ONE row — the culled
   `mgk-viii-cover.jpg`, whose file this round deleted. Three instruments broke
   on one cause in one round: this guard, the disk check thirty lines up, and
   `usedBy` in tools/asset-table.mjs, which would have condemned twenty-six
   photographs as unreferenced. **A picture has two addresses now, and anything
   that matches on one of them is wrong.** The guard itself is untouched in
   substance and still refuses a genuine deletion. */
if (process.argv.includes("--write")) {
  const at = path.join(REPO, "provenance", "assets.json");
  if (fs.existsSync(at)) {
    const live = JSON.parse(fs.readFileSync(at, "utf8")).entries || {};
    const declared = new Set(Object.values(entries).map((e) => e.ref));
    /* the public address of a ref that may be written either way round */
    const pub = (r) => r.startsWith(STAGE_PREFIX + "/") ? r.slice(STAGE_PREFIX.length) : r;
    const lost = Object.values(live).map((e) => e.ref)
      .filter((r) => !declared.has(r) && !declared.has(pub(r)));
    if (lost.length) {
      console.error(
        "\nREFUSED — writing would delete " + lost.length + " declaration(s) that exist" + 
        "\nin provenance/assets.json and are NOT in this file's array. That is M99, and" + 
        "\nit is what this guard exists for: the declarer has drifted from the file it" + 
        "\nwrites, so a --write is a silent deletion rather than a regeneration.\n\n" +
        lost.map((r) => "  " + r).join("\n") +
        "\n\nEither add them to A above, or decide assets.json is the source and retire" + 
        "\nthis generator. See OPEN_ACTIONS H-b.");
      process.exit(1);
    }
  }
  fs.writeFileSync(at, JSON.stringify(out, null, 1) + "\n");
  console.log("wrote provenance/assets.json");
}
const withText = A.filter((a) => a[3]).length;
console.log(`${A.length} assets declared · ${withText} carry text in the image · ${missing} missing on disk`);
