# WRITE SCRIPT — writes exactly these paths, nothing else:
#   C:\AI\Projects\weird-baby-museum\src\data\exhibits\hunter_root.json   (regenerated by export)
#   C:\AI\Projects\weird-baby-museum\src\data\vocabulary.json             (regenerated by export)
#   $env:TEMP\hr_head.json, $env:TEMP\mv_stage3_diff.py                   (throwaway)
# PREREQ: MV server RUNNING (launch_mediavault.bat). PowerShell 7.
# NOTE: export-artifacts prints a harmless UV_HANDLE_CLOSING assertion AFTER
# finishing — documented hazard, ignore it.

Set-Location 'C:\AI\Projects\weird-baby-museum'
git show HEAD:src/data/exhibits/hunter_root.json | Set-Content -LiteralPath (Join-Path $env:TEMP 'hr_head.json') -Encoding utf8NoBOM
npm run export-artifacts

$py = Join-Path $env:TEMP 'mv_stage3_diff.py'
$code = @'
import json, os

def pairs(node, out):
    if isinstance(node, dict):
        if 'id' in node and 'source_platform' in node:
            out.append((node['id'], node['source_platform']))
        for v in node.values(): pairs(v, out)
    elif isinstance(node, list):
        for v in node: pairs(v, out)
    return out

old = pairs(json.load(open(os.path.join(os.environ['TEMP'], 'hr_head.json'), encoding='utf-8')), [])
new = pairs(json.load(open(r'C:\AI\Projects\weird-baby-museum\src\data\exhibits\hunter_root.json', encoding='utf-8')), [])
oldm, newm = dict(old), dict(new)
yt_old = {i for i, s in oldm.items() if s == 'youtube'}
yt_new = {i for i, s in newm.items() if s == 'youtube'}
print('records with (id, source_platform): HEAD %d -> new %d' % (len(oldm), len(newm)))
print('YOUTUBE source_platform set UNCHANGED (critical):', yt_old == yt_new, '(%d ids)' % len(yt_new))
changed = sorted((i, oldm.get(i), newm.get(i)) for i in set(oldm) | set(newm) if oldm.get(i) != newm.get(i))
print('source_platform changes (expect only None/absent -> local):')
for c in changed: print('  ', c)
print('STAGE3_DIFF_DONE')
'@
Set-Content -LiteralPath $py -Value $code -Encoding utf8NoBOM
python $py

Write-Host '--- GIT VIEW OF REGENERATED FILES ---'
git -C 'C:\AI\Projects\weird-baby-museum' status --short
git -C 'C:\AI\Projects\weird-baby-museum' diff --stat -- src/data/exhibits/hunter_root.json src/data/vocabulary.json
Write-Host 'STAGE3B_SCRIPT_DONE'
