# WRITE SCRIPT — writes exactly these paths, nothing else:
#   C:\AI\Projects\weird-baby-museum\src\data\exhibits\hunter_root.json   (regenerated by export)
#   C:\AI\Projects\weird-baby-museum\src\data\vocabulary.json             (regenerated by export)
#   $env:TEMP\mv_stage4_diff.py                                           (throwaway)
# PREREQ: MV server RUNNING. PowerShell 7.
# Ignore the harmless trailing UV_HANDLE_CLOSING assertion from the exporter.

Set-Location 'C:\AI\Projects\weird-baby-museum'
npm run export-artifacts

$py = Join-Path $env:TEMP 'mv_stage4_diff.py'
$code = @'
import json, re

hr = open(r'C:\AI\Projects\weird-baby-museum\src\data\exhibits\hunter_root.json', encoding='utf-8').read()
print('"bands" keys in hunter_root.json (expect 0):', len(re.findall(r'"bands"\s*:', hr)))
print('"band" keys in hunter_root.json (expect >0):', len(re.findall(r'"band"\s*:', hr)))
print('bands: tag strings (expect 0):', hr.count('bands:'))
print('band:hunter_root strings:', hr.count('band:hunter_root'))
voc = json.load(open(r'C:\AI\Projects\weird-baby-museum\src\data\vocabulary.json', encoding='utf-8'))
rows = voc if isinstance(voc, list) else voc.get('rows', voc.get('namespaces', []))
names = [r.get('namespace') for r in rows if isinstance(r, dict)]
print('vocabulary.json namespaces:', sorted(n for n in names if n))
print('has band (expect True):', 'band' in names, '| has bands (expect False):', 'bands' in names)
print('STAGE4_DIFF_DONE')
'@
Set-Content -LiteralPath $py -Value $code -Encoding utf8NoBOM
python $py

Write-Host '--- GIT VIEW ---'
git -C 'C:\AI\Projects\weird-baby-museum' status --short
git -C 'C:\AI\Projects\weird-baby-museum' diff --stat -- src/data/exhibits/hunter_root.json src/data/vocabulary.json src/routes/hr/HrExhibitFlow.jsx
Write-Host 'STAGE4B_SCRIPT_DONE'
